---
name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "main"
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux, windows, freebsd, netbsd, openbsd]
        goarch: [amd64, arm, arm64, "386"]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: darwin
    steps:
    - uses: actions/checkout@main
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        md5sum: false
        sha256sum: true
        compress_assets: auto
        extra_files: LICENSE README.md
