---
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
    build-release:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout 🛎
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Set up Go ⚙️
          uses: actions/setup-go@v4
          with:
            go-version: '>=1.18.0'

        - name: Release Go binaries 🎁
          uses: goreleaser/goreleaser-action@master
          with:
            version: latest
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}