---
name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@main
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GH_PAT }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        md5sum: false
        sha256sum: true
        compress_assets: auto
        extra_files: LICENSE README.md
